
import type { Metadata } from "next";
import Providers from "./components/Provider";
import { Figtree } from "next/font/google";
import "./globals.css";

const figtree = Figtree({ weight: ['400', '700', '800'], subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (

    <html lang="en">
      <body className={figtree.className}>
        <Providers>{children}</Providers></body>
    </html>

  );
}
